### ISSUE TITLE
ghmattimysql and cops fivem

### ISSUE THREAD

**Issue by Therippers** [GHMatti/ghmattimysql#12]
Error: (node:12400) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
    --------------------
    at Protocol._enqueue (ghmattimysql.js:308:2850)
    at Protocol.handshake (ghmattimysql.js:308:1096)
    at PoolConnection.connect (ghmattimysql.js:140:2921)
    at Pool.getConnection (ghmattimysql.js:260:1073)
    at Pool.query (ghmattimysql.js:260:3806)
    at Promise (ghmattimysql.js:278:1421)
    at new Promise (<anonymous>)
    at execute (ghmattimysql.js:278:1386)
    at Object.global.exports [as callback] (ghmattimysql.js:278:2014)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:12400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Error: (node:12400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by GHMatti** [comment]
This might be an issue with mysql.js and (I am bluntly assuming) xampp you are using.

it'd be better to use mariadb.
