### ISSUE TITLE
Error: ER_NOT_SUPPORTED_AUTH_MODE for caching_sha2_password

### ISSUE THREAD

**Issue by Drift91** [GHMatti/ghmattimysql#5]
This resource appears to be incompatible with the latest authentication protocol used by MySQL 8.0.

While Googling the error message I received I found this issue on what I suspect is the library you've used:
https://github.com/mysqljs/mysql/issues/1507#issuecomment-385810339

In case you need it, here's the full error:
```
Uncaught AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
internal/errors.js(102,11): AssertionError
assert.js(42,9): innerFail
assert.js(56,3): fail
internal/process/promises.js(27,25):
ghmattimysql.js(278,1556): orm.query
ghmattimysql.js(109,1512): Sequence.end
ghmattimysql.js(260,3884):
ghmattimysql.js(260,1314): onConnect
ghmattimysql.js(109,1512): Sequence.end
ghmattimysql.js(489,3184): Handshake.ErrorPacket

AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
Error: (node:5744) UnhandledPromiseRejectionWarning: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (ghmattimysql.js:109:1148)
    at Handshake.ErrorPacket (ghmattimysql.js:489:3136)
    at Protocol._parsePacket (ghmattimysql.js:308:5471)
    at Parser.write (ghmattimysql.js:314:1645)
    at Protocol.write (ghmattimysql.js:308:875)
    at Socket.<anonymous> (ghmattimysql.js:140:2050)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (ghmattimysql.js:308:2850)
    at Protocol.handshake (ghmattimysql.js:308:1096)
    at PoolConnection.connect (ghmattimysql.js:140:2921)
    at Pool.getConnection (ghmattimysql.js:260:1073)
    at Pool.query (ghmattimysql.js:260:3806)
    at Promise (ghmattimysql.js:278:1421)
    at new Promise (<anonymous>)
    at execute (ghmattimysql.js:278:1386)
    at Object.global.exports [as callback] (ghmattimysql.js:278:2014)
    at citizen:/scripting/v8/main.js:87:41
Error: (node:5744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Error: (node:5744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Drift91** [comment]
As a workaround for anyone else experiencing this issue, here's what I used as a workaround:
`ALTER USER 'yourusername'@'localhost' IDENTIFIED WITH mysql_native_password BY 'youpassword';`

**Comment by GHMatti** [comment]
You should not be running mysql8, it has performance issues on all connectors not just mysql.js
